### ISSUE TITLE
Add Spark.awaitStop() to after()

### ISSUE THREAD

**Issue by victornoel** [ferwasy/spark-test#1]
See https://github.com/despegar/spark-test/issues/14.

Basically, it is needed to to get `Spark.awaitStop()` added to the `after()` method to ensure the Spark server is properly stopped (because `stop()` executes in a `Thread`).

**Comment by ferwasy** [comment]
Hi @victornoel. This change has been included in the version 1.2.0. Unfortunately I cannot upload a new artifact version to central repository yet, because I had to change the groupId (I no longer work for Despegar) and I have to register the domain. Until then, please build the develop branch and release it locally.
Regards
Fernando.

**Comment by victornoel** [comment]
@ferwasy thank you, do you have some kind of ETA of when this will be available on Maven central or an issue to track the progress? Cheers
